export const COUNTRIES = [
  { label: 'Afganistan', value: 'Afghanistan', code: 'AF' },
  { label: 'Albania', value: 'Albania', code: 'AL' },
  { label: 'Algieria', value: 'Algeria', code: 'DZ' },
  { label: 'Andora', value: 'Andorra', code: 'AD' },
  { label: 'Angola', value: 'Angola', code: 'AO' },
  { label: 'Anguilla', value: 'Anguilla', code: 'AI' },
  { label: 'Antarktyka', value: 'Antarctica', code: 'AQ' },
  { label: 'Antigua i Barbuda', value: 'Antigua and Barbuda', code: 'AG' },
  { label: 'Arabia Saudyjska', value: 'Saudi Arabia', code: 'SA' },
  { label: 'Argentyna', value: 'Argentina', code: 'AR' },
  { label: 'Armenia', value: 'Armenia', code: 'AM' },
  { label: 'Aruba', value: 'Aruba', code: 'AW' },
  { label: 'Australia', value: 'Australia', code: 'AU' },
  { label: 'Austria', value: 'Austria', code: 'AT' },
  { label: 'Azerbejdżan', value: 'Azerbaijan', code: 'AZ' },
  { label: 'Bahamy', value: 'Bahamas', code: 'BS' },
  { label: 'Bahrajn', value: 'Bahrain', code: 'BH' },
  { label: 'Bangladesz', value: 'Bangladesh', code: 'BD' },
  { label: 'Barbados', value: 'Barbados', code: 'BB' },
  { label: 'Belgia', value: 'Belgium', code: 'BE' },
  { label: 'Belize', value: 'Belize', code: 'BZ' },
  { label: 'Benin', value: 'Benin', code: 'BJ' },
  { label: 'Bermudy', value: 'Bermuda', code: 'BM' },
  { label: 'Bhutan', value: 'Bhutan', code: 'BT' },
  { label: 'Białoruś', value: 'Belarus', code: 'BY' },
  { label: 'Boliwia', value: 'Bolivia', code: 'BO' },
  {
    label: 'Bonaire, Sint Eustatius i Saba',
    value: 'Bonaire Sint Eustatius and Saba',
    code: 'BQ',
  },
  {
    label: 'Bośnia i Hercegowina',
    value: 'Bosnia and Herzegovina',
    code: 'BA',
  },
  { label: 'Botswana', value: 'Botswana', code: 'BW' },
  { label: 'Brazylia', value: 'Brazil', code: 'BR' },
  { label: 'Brunei', value: 'Brunei Darussalam', code: 'BN' },
  {
    label: 'Brytyjskie Terytorium Oceanu Indyjskiego',
    value: 'British Indian Ocean Territory',
    code: 'IO',
  },
  {
    label: 'Brytyjskie Wyspy Dziewicze',
    value: 'Virgin Islands British',
    code: 'VG',
  },
  { label: 'Bułgaria', value: 'Bulgaria', code: 'BG' },
  { label: 'Burkina Faso', value: 'Burkina Faso', code: 'BF' },
  { label: 'Burundi', value: 'Burundi', code: 'BI' },
  { label: 'Chile', value: 'Chile', code: 'CL' },
  { label: 'Chiny', value: 'China', code: 'CN' },
  { label: 'Chorwacja', value: 'Croatia', code: 'HR' },
  { label: 'Curaçao', value: 'Curaçao', code: 'CW' },
  { label: 'Cypr', value: 'Cyprus', code: 'CY' },
  { label: 'Czad', value: 'Chad', code: 'TD' },
  { label: 'Czarnogóra', value: 'Montenegro', code: 'ME' },
  { label: 'Czechy', value: 'Czech Republic', code: 'CZ' },
  {
    label: 'Dalekie Wyspy Mniejsze Stanów Zjednoczonych',
    value: 'United States Minor Outlying Islands',
    code: 'UM',
  },
  { label: 'Dania', value: 'Denmark', code: 'DK' },
  {
    label: 'Demokratyczna Republika Konga',
    value: 'Congo the Democratic Republic of the',
    code: 'CD',
  },
  { label: 'Dominika', value: 'Dominica', code: 'DM' },
  { label: 'Dominikana', value: 'Dominican Republic', code: 'DO' },
  { label: 'Dżibuti', value: 'Djibouti', code: 'DJ' },
  { label: 'Egipt', value: 'Egypt', code: 'EG' },
  { label: 'Ekwador', value: 'Ecuador', code: 'EC' },
  { label: 'Erytrea', value: 'Eritrea', code: 'ER' },
  { label: 'Estonia', value: 'Estonia', code: 'EE' },
  { label: 'Etiopia', value: 'Ethiopia', code: 'ET' },
  { label: 'Falklandy', value: 'Falkland Islands (Malvinas)', code: 'FK' },
  { label: 'Fidżi', value: 'Fiji', code: 'FJ' },
  { label: 'Filipiny', value: 'Philippines', code: 'PH' },
  { label: 'Finlandia', value: 'Finland', code: 'FI' },
  { label: 'Francja', value: 'France', code: 'FR' },
  {
    label: 'Francuskie Terytoria Południowe i Antarktyczne',
    value: 'French Southern Territories',
    code: 'TF',
  },
  { label: 'Gabon', value: 'Gabon', code: 'GA' },
  { label: 'Gambia', value: 'Gambia', code: 'GM' },
  {
    label: 'Georgia Południowa i Sandwich Południowy',
    value: 'South Georgia and the South Sandwich Islands',
    code: 'GS',
  },
  { label: 'Ghana', value: 'Ghana', code: 'GH' },
  { label: 'Gibraltar', value: 'Gibraltar', code: 'GI' },
  { label: 'Grecja', value: 'Greece', code: 'GR' },
  { label: 'Grenada', value: 'Grenada', code: 'GD' },
  { label: 'Grenlandia', value: 'Greenland', code: 'GL' },
  { label: 'Gruzja', value: 'Georgia', code: 'GE' },
  { label: 'Guam', value: 'Guam', code: 'GU' },
  { label: 'Guernsey', value: 'Guernsey', code: 'GG' },
  { label: 'Gujana Francuska', value: 'French Guiana', code: 'GF' },
  { label: 'Gujana', value: 'Guyana', code: 'GY' },
  { label: 'Gwadelupa', value: 'Guadeloupe', code: 'GP' },
  { label: 'Gwatemala', value: 'Guatemala', code: 'GT' },
  { label: 'Gwinea Bissau', value: 'Guinea Bissau', code: 'GW' },
  { label: 'Gwinea Równikowa', value: 'Equatorial Guinea', code: 'GQ' },
  { label: 'Gwinea', value: 'Guinea', code: 'GN' },
  { label: 'Haiti', value: 'Haiti', code: 'HT' },
  { label: 'Hiszpania', value: 'Spain', code: 'ES' },
  { label: 'Holandia', value: 'Netherlands', code: 'NL' },
  { label: 'Honduras', value: 'Honduras', code: 'HN' },
  { label: 'Hongkong', value: 'Hong Kong', code: 'HK' },
  { label: 'Indie', value: 'India', code: 'IN' },
  { label: 'Indonezja', value: 'Indonesia', code: 'ID' },
  { label: 'Irak', value: 'Iraq', code: 'IQ' },
  { label: 'Iran', value: 'Iran Islamic Republic of', code: 'IR' },
  { label: 'Irlandia', value: 'Ireland', code: 'IE' },
  { label: 'Islandia', value: 'Iceland', code: 'IS' },
  { label: 'Izrael', value: 'Israel', code: 'IL' },
  { label: 'Jamajka', value: 'Jamaica', code: 'JM' },
  { label: 'Japonia', value: 'Japan', code: 'JP' },
  { label: 'Jemen', value: 'Yemen', code: 'YE' },
  { label: 'Jersey', value: 'Jersey', code: 'JE' },
  { label: 'Jordania', value: 'Jordan', code: 'JO' },
  { label: 'Kajmany', value: 'Cayman Islands', code: 'KY' },
  { label: 'Kambodża', value: 'Cambodia', code: 'KH' },
  { label: 'Kamerun', value: 'Cameroon', code: 'CM' },
  { label: 'Kanada', value: 'Canada', code: 'CA' },
  { label: 'Katar', value: 'Qatar', code: 'QA' },
  { label: 'Kazachstan', value: 'Kazakhstan', code: 'KZ' },
  { label: 'Kenia', value: 'Kenya', code: 'KE' },
  { label: 'Kirgistan', value: 'Kyrgyzstan', code: 'KG' },
  { label: 'Kiribati', value: 'Kiribati', code: 'KI' },
  { label: 'Kolumbia', value: 'Colombia', code: 'CO' },
  { label: 'Komory', value: 'Comoros', code: 'KM' },
  { label: 'Kongo', value: 'Congo', code: 'CG' },
  { label: 'Korea Południowa', value: 'Korea Republic of', code: 'KR' },
  {
    label: 'Korea Północna',
    value: 'Korea Democratic Peoples Republic of',
    code: 'KP',
  },
  { label: 'Kostaryka', value: 'Costa Rica', code: 'CR' },
  { label: 'Kuba', value: 'Cuba', code: 'CU' },
  { label: 'Kuwejt', value: 'Kuwait', code: 'KW' },
  { label: 'Laos', value: 'Lao People s Democratic Republic', code: 'LA' },
  { label: 'Lesotho', value: 'Lesotho', code: 'LS' },
  { label: 'Liban', value: 'Lebanon', code: 'LB' },
  { label: 'Liberia', value: 'Liberia', code: 'LR' },
  { label: 'Libia', value: 'Libyan Arab Jamahiriya', code: 'LY' },
  { label: 'Liechtenstein', value: 'Liechtenstein', code: 'LI' },
  { label: 'Litwa', value: 'Lithuania', code: 'LT' },
  { label: 'Luksemburg', value: 'Luxembourg', code: 'LU' },
  { label: 'Łotwa', value: 'Latvia', code: 'LV' },
  {
    label: 'Macedonia',
    value: 'Macedonia the former Yugoslav Republic of',
    code: 'MK',
  },
  { label: 'Madagaskar', value: 'Madagascar', code: 'MG' },
  { label: 'Majotta', value: 'Mayotte', code: 'YT' },
  { label: 'Makau', value: 'Macao', code: 'MO' },
  { label: 'Malawi', value: 'Malawi', code: 'MW' },
  { label: 'Malediwy', value: 'Maldives', code: 'MV' },
  { label: 'Malezja', value: 'Malaysia', code: 'MY' },
  { label: 'Mali', value: 'Mali', code: 'ML' },
  { label: 'Malta', value: 'Malta', code: 'MT' },
  { label: 'Mariany Północne', value: 'Northern Mariana Islands', code: 'MP' },
  { label: 'Maroko', value: 'Morocco', code: 'MA' },
  { label: 'Martynika', value: 'Martinique', code: 'MQ' },
  { label: 'Mauretania', value: 'Mauritania', code: 'MR' },
  { label: 'Mauritius', value: 'Mauritius', code: 'MU' },
  { label: 'Meksyk', value: 'Mexico', code: 'MX' },
  { label: 'Mikronezja', value: 'Micronesia', code: 'FM' },
  { label: 'Mjanma', value: 'Myanmar', code: 'MM' },
  { label: 'Mołdawia', value: 'Moldova Republic of', code: 'MD' },
  { label: 'Monako', value: 'Monaco', code: 'MC' },
  { label: 'Mongolia', value: 'Mongolia', code: 'MN' },
  { label: 'Montserrat', value: 'Montserrat', code: 'MS' },
  { label: 'Mozambik', value: 'Mozambique', code: 'MZ' },
  { label: 'Namibia', value: 'Namibia', code: 'NA' },
  { label: 'Nauru', value: 'Nauru', code: 'NR' },
  { label: 'Nepal', value: 'Nepal', code: 'NP' },
  { label: 'Niemcy', value: 'Germany', code: 'DE' },
  { label: 'Niger', value: 'Niger', code: 'NE' },
  { label: 'Nigeria', value: 'Nigeria', code: 'NG' },
  { label: 'Nikaragua', value: 'Nicaragua', code: 'NI' },
  { label: 'Niue', value: 'Niue', code: 'NU' },
  { label: 'Norfolk', value: 'Norfolk Island', code: 'NF' },
  { label: 'Norwegia', value: 'Norway', code: 'NO' },
  { label: 'Nowa Kaledonia', value: 'New Caledonia', code: 'NC' },
  { label: 'Nowa Zelandia', value: 'New Zealand', code: 'NZ' },
  { label: 'Oman', value: 'Oman', code: 'OM' },
  { label: 'Pakistan', value: 'Pakistan', code: 'PK' },
  { label: 'Palau', value: 'Palau', code: 'PW' },
  { label: 'Palestyna', value: 'Palestinian Territory', code: 'PS' },
  { label: 'Panama', value: 'Panama', code: 'PA' },
  { label: 'Papua-Nowa Gwinea', value: 'Papua New Guinea', code: 'PG' },
  { label: 'Paragwaj', value: 'Paraguay', code: 'PY' },
  { label: 'Peru', value: 'Peru', code: 'PE' },
  { label: 'Pitcairn', value: 'Pitcairn', code: 'PN' },
  { label: 'Polinezja Francuska', value: 'French Polynesia', code: 'PF' },
  { label: 'Polska', value: 'Poland', code: 'PL' },
  { label: 'Portoryko', value: 'Puerto Rico', code: 'PR' },
  { label: 'Portugalia', value: 'Portugal', code: 'PT' },
  { label: 'Republika Południowej Afryki', value: 'South Africa', code: 'ZA' },
  {
    label: 'Republika Środkowoafrykańska',
    value: 'Central African Republic',
    code: 'CF',
  },
  { label: 'Republika Zielonego Przylądka', value: 'Cape Verde', code: 'CV' },
  { label: 'Reunion', value: 'Réunion', code: 'RE' },
  { label: 'Rosja', value: 'Russian Federation', code: 'RU' },
  { label: 'Rumunia', value: 'Romania', code: 'RO' },
  { label: 'Rwanda', value: 'Rwanda', code: 'RW' },
  { label: 'Sahara Zachodnia', value: 'Western Sahara', code: 'EH' },
  { label: 'Saint Kitts i Nevis', value: 'Saint Kitts and Nevis', code: 'KN' },
  { label: 'Saint Lucia', value: 'Saint Lucia', code: 'LC' },
  {
    label: 'Saint Vincent i Grenadyny',
    value: 'Saint Vincent and the Grenadines',
    code: 'VC',
  },
  { label: 'Saint-Barthélemy', value: 'Saint Barthelemy', code: 'BL' },
  { label: 'Saint-Martin', value: 'Saint Martin French part', code: 'MF' },
  {
    label: 'Saint-Pierre i Miquelon',
    value: 'Saint Pierre and Miquelon',
    code: 'PM',
  },
  { label: 'Salwador', value: 'El Salvador', code: 'SV' },
  { label: 'Samoa Amerykańskie', value: 'American Samoa', code: 'AS' },
  { label: 'Samoa', value: 'Samoa', code: 'WS' },
  { label: 'San Marino', value: 'San Marino', code: 'SM' },
  { label: 'Senegal', value: 'Senegal', code: 'SN' },
  { label: 'Serbia', value: 'Serbia', code: 'RS' },
  { label: 'Seszele', value: 'Seychelles', code: 'SC' },
  { label: 'Sierra Leone', value: 'Sierra Leone', code: 'SL' },
  { label: 'Singapur', value: 'Singapore', code: 'SG' },
  { label: 'Sint Maarten', value: 'Sint Maarten Dutch part', code: 'SX' },
  { label: 'Słowacja', value: 'Slovakia', code: 'SK' },
  { label: 'Słowenia', value: 'Slovenia', code: 'SI' },
  { label: 'Somalia', value: 'Somalia', code: 'SO' },
  { label: 'Sri Lanka', value: 'Sri Lanka', code: 'LK' },
  { label: 'Stany Zjednoczone', value: 'United States', code: 'US' },
  { label: 'Suazi', value: 'Swaziland', code: 'SZ' },
  { label: 'Sudan', value: 'Sudan', code: 'SD' },
  { label: 'Sudan Południowy', value: 'South Sudan', code: 'SS' },
  { label: 'Surinam', value: 'Suriname', code: 'SR' },
  {
    label: 'Svalbard i Jan Mayen',
    value: 'Svalbard and Jan Mayen',
    code: 'SJ',
  },
  { label: 'Syria', value: 'Syrian Arab Republic', code: 'SY' },
  { label: 'Szwajcaria', value: 'Switzerland', code: 'CH' },
  { label: 'Szwecja', value: 'Sweden', code: 'SE' },
  { label: 'Tadżykistan', value: 'Tajikistan', code: 'TJ' },
  { label: 'Tajlandia', value: 'Thailand', code: 'TH' },
  { label: 'Tajwan', value: 'Taiwan, Province of China', code: 'TW' },
  { label: 'Tanzania', value: 'Tanzania United Republic of', code: 'TZ' },
  { label: 'Timor Wschodni', value: 'Timor Leste', code: 'TL' },
  { label: 'Togo', value: 'Togo', code: 'TG' },
  { label: 'Tokelau', value: 'Tokelau', code: 'TK' },
  { label: 'Tonga', value: 'Tonga', code: 'TO' },
  { label: 'Trynidad i Tobago', value: 'Trinidad and Tobago', code: 'TT' },
  { label: 'Tunezja', value: 'Tunisia', code: 'TN' },
  { label: 'Turcja', value: 'Turkey', code: 'TR' },
  { label: 'Turkmenistan', value: 'Turkmenistan', code: 'TM' },
  { label: 'Turks i Caicos', value: 'Turks and Caicos Islands', code: 'TC' },
  { label: 'Tuvalu', value: 'Tuvalu', code: 'TV' },
  { label: 'Uganda', value: 'Uganda', code: 'UG' },
  { label: 'Ukraina', value: 'Ukraine', code: 'UA' },
  { label: 'Urugwaj', value: 'Uruguay', code: 'UY' },
  { label: 'Uzbekistan', value: 'Uzbekistan', code: 'UZ' },
  { label: 'Vanuatu', value: 'Vanuatu', code: 'VU' },
  { label: 'Wallis i Futuna', value: 'Wallis and Futuna', code: 'WF' },
  { label: 'Watykan', value: 'Holy See Vatican City State', code: 'VA' },
  { label: 'Wenezuela', value: 'Venezuela Bolivarian Republic of', code: 'VE' },
  { label: 'Węgry', value: 'Hungary', code: 'HU' },
  { label: 'Wielka Brytania', value: 'United Kingdom', code: 'GB' },
  { label: 'Wietnam', value: 'Viet Nam', code: 'VN' },
  { label: 'Włochy', value: 'Italy', code: 'IT' },
  { label: 'Wybrzeże Kości Słoniowej', value: 'Cote dIvoire', code: 'CI' },
  { label: 'Wyspa Bouveta', value: 'Bouvet Island', code: 'BV' },
  { label: 'Wyspa Bożego Narodzenia', value: 'Christmas Island', code: 'CX' },
  { label: 'Wyspa Man', value: 'Isle of Man', code: 'IM' },
  {
    label: 'Wyspa Świętej Heleny, Wyspa Wniebowstąpienia i Tristan da Cunha',
    value: 'Saint Helena Ascension and Tristan Cunha',
    code: 'SH',
  },
  { label: 'Wyspy Alandzkie', value: 'Aland Islands', code: 'AX' },
  { label: 'Wyspy Cooka', value: 'Cook Islands', code: 'CK' },
  {
    label: 'Wyspy Dziewicze Stanów Zjednoczonych',
    value: 'Virgin Islands U S',
    code: 'VI',
  },
  {
    label: 'Wyspy Heard i McDonalda',
    value: 'Heard Island and McDonald Islands',
    code: 'HM',
  },
  { label: 'Wyspy Kokosowe', value: 'Cocos Islands', code: 'CC' },
  { label: 'Wyspy Marshalla', value: 'Marshall Islands', code: 'MH' },
  { label: 'Wyspy Owcze', value: 'Faroe Islands', code: 'FO' },
  { label: 'Wyspy Salomona', value: 'Solomon Islands', code: 'SB' },
  {
    label: 'Wyspy Świętego Tomasza i Książęca',
    value: 'Sao Tome and Principe',
    code: 'ST',
  },
  { label: 'Zambia', value: 'Zambia', code: 'ZM' },
  { label: 'Zimbabwe', value: 'Zimbabwe', code: 'ZW' },
  {
    label: 'Zjednoczone Emiraty Arabskie',
    value: 'United Arab Emirates',
    code: 'AE',
  },
] as const;
